name: electroassist
description: Assistant for electrical enthusiasts.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_animator: ^3.1.2
  bouncing_widget: ^2.0.0
  animations: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
